// ─── Multimodal — Media-Text Disagreement ────────────────────────────────
// Detects conflicts between what the post text says and what the media shows.
//
// Media-text disagreement is a caution flag — it does NOT mean the media is
// wrong or the text is wrong, but it means confident claims should be hedged.
//
// Design constraints:
//   • Pure functions — no I/O.
//   • Fail-closed on any error.
//   • Returns caution flags, not UI strings.

import { clamp01 } from '../context/limits';

// ─── Types ────────────────────────────────────────────────────────────────

export type MediaDisagreementKind =
  | 'sentiment_mismatch'   // text says positive but image appears negative (or vice versa)
  | 'claim_mismatch'       // OCR text contradicts the post's stated claim
  | 'entity_mismatch'      // image shows different entity than text claims
  | 'context_mismatch'     // image appears from a different context/time
  | 'fabrication_risk'     // image may be manipulated or out of context
  | 'low_confidence';      // model confidence too low to draw conclusions

export interface MediaDisagreementResult {
  /** Overall disagreement level [0, 1]. */
  disagreementLevel: number;
  /** Specific types of disagreement detected. */
  disagreements: MediaDisagreementKind[];
  /** Caution flags for the writer (short human-readable strings). */
  cautionFlags: string[];
  /** Whether to suppress confident claims about this media. */
  suppressConfidentClaims: boolean;
}

// ─── Sentiment mismatch detection ─────────────────────────────────────────

const POSITIVE_CLAIM_PATTERNS = [
  /\b(?:great|excellent|amazing|wonderful|fantastic|success|win|victory|achievement|landmark|historic)\b/i,
];
const NEGATIVE_CLAIM_PATTERNS = [
  /\b(?:terrible|awful|disaster|failure|crisis|scandal|shame|disgrace|outrage)\b/i,
];

// ─── Fabrication risk patterns ────────────────────────────────────────────

const FABRICATION_RISK_PATTERNS = [
  /\b(?:photoshopped|manipulated|edited|doctored|faked|fake|deepfake|ai-generated|ai generated|generated with ai|generated by ai)\b/i,
  /\b(?:out of context|misrepresented|misleading image|old (?:photo|image|video)|from \d{4})\b/i,
];

// ─── detectMediaTextDisagreement ──────────────────────────────────────────

/**
 * Detect conflicts between post text and extracted media content.
 *
 * @param postText      — the full post text
 * @param ocrText       — OCR-extracted text from the media (if available)
 * @param mediaSummary  — brief prose summary from the vision model (if available)
 * @param modelConfidence — vision model's self-reported confidence [0, 1]
 * @param cautionFlagsFromModel — any caution flags the vision model returned
 *
 * Never throws.
 */
export function detectMediaTextDisagreement(
  postText: string,
  ocrText?: string,
  mediaSummary?: string,
  modelConfidence?: number,
  cautionFlagsFromModel?: string[],
): MediaDisagreementResult {
  const safe: MediaDisagreementResult = {
    disagreementLevel: 0,
    disagreements: [],
    cautionFlags: [],
    suppressConfidentClaims: false,
  };

  try {
    const pt = (postText ?? '').slice(0, 800).toLowerCase();
    const ocr = (ocrText ?? '').slice(0, 800).toLowerCase();
    const summary = (mediaSummary ?? '').slice(0, 400).toLowerCase();

    const disagreements: MediaDisagreementKind[] = [];
    const cautionFlags: string[] = [];

    // 1. Low model confidence
    if (Number.isFinite(modelConfidence) && (modelConfidence as number) < 0.30) {
      disagreements.push('low_confidence');
      cautionFlags.push('Low visual analysis confidence');
    }

    // 2. Fabrication risk (from either post text or model flags)
    const fabricationInPost = FABRICATION_RISK_PATTERNS.some(p => p.test(pt));
    const fabricationInSummary = FABRICATION_RISK_PATTERNS.some(p => p.test(summary));
    if (fabricationInPost || fabricationInSummary) {
      disagreements.push('fabrication_risk');
      cautionFlags.push('Possible out-of-context or manipulated media');
    }

    // 3. Sentiment mismatch: post is positive but summary seems negative (or vice versa)
    if (summary.length > 20 && pt.length > 20) {
      const postPositive = POSITIVE_CLAIM_PATTERNS.some(p => p.test(pt));
      const postNegative = NEGATIVE_CLAIM_PATTERNS.some(p => p.test(pt));
      const summaryPositive = POSITIVE_CLAIM_PATTERNS.some(p => p.test(summary));
      const summaryNegative = NEGATIVE_CLAIM_PATTERNS.some(p => p.test(summary));
      if ((postPositive && summaryNegative) || (postNegative && summaryPositive)) {
        disagreements.push('sentiment_mismatch');
        cautionFlags.push('Post tone may not match image content');
      }
    }

    // 4. OCR vs post text mismatch: OCR has numbers/data that conflict with post
    if (ocr.length > 20 && pt.length > 20) {
      // Extract numbers from each
      const ptNums = (pt.match(/\b\d[\d,]*(?:\.\d+)?(?:\s*%|\s*percent)?\b/g) ?? []).map(n => n.replace(/,/g, ''));
      const ocrNums = (ocr.match(/\b\d[\d,]*(?:\.\d+)?(?:\s*%|\s*percent)?\b/g) ?? []).map(n => n.replace(/,/g, ''));

      if (ptNums.length > 0 && ocrNums.length > 0) {
        // If post cites a number that is NOT in the OCR text, that is a mismatch signal
        const ptUnique = ptNums.filter(n => !ocrNums.some(o => Math.abs(parseFloat(o) - parseFloat(n)) < 0.01));
        if (ptUnique.length > 0 && ocrNums.length > 0) {
          disagreements.push('claim_mismatch');
          cautionFlags.push('Numerical data in post may not match image');
        }
      }
    }

    // 5. Incorporate model-returned caution flags
    if (cautionFlagsFromModel?.length) {
      const normalized = cautionFlagsFromModel.slice(0, 4).map(f => String(f).slice(0, 80));
      cautionFlags.push(...normalized);
    }

    const disagreementLevel = clamp01(disagreements.length * 0.25);
    const suppressConfidentClaims =
      disagreements.includes('fabrication_risk') ||
      disagreements.includes('claim_mismatch') ||
      disagreementLevel >= 0.50;

    return {
      disagreementLevel,
      disagreements,
      cautionFlags: [...new Set(cautionFlags)].slice(0, 5),
      suppressConfidentClaims,
    };
  } catch {
    return safe;
  }
}
